name: 提示词模板
description: 如有好的提示词或是提示词想法，欢迎投稿和建议。
title: "[Prompt]"
labels:
  - documentation
labels:
  - bug
assignees: rockbenben
body:
  - type: textarea
    id: prompt-title
    attributes:
      label: 提示词标题
      placeholder: 提示词标题（默认中文）
    validations:
      required: true

  - type: textarea
    id: prompt-content
    attributes:
      label: 提示词内容
      description: 提示词内容可以提交多种语言，或简单描述提示词想法。
      placeholder: 提示词内容可以提交多种语言，或简单描述提示词想法。
    validations:
      required: true

  - type: textarea
    id: prompt-role
    attributes:
      label: 提示词作用
      placeholder: 简单描述提示词的作用。
